apiVersion: apps/v1
kind: Deployment
metadata:
  name: longping
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: longping
  template:
    metadata:
      labels:
        app: longping
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: longping
        image: cheetahfox/longping:latest
        ports:
        - containerPort: 3000
          name: http-port
          protocol: TCP
        envFrom:
        - configMapRef:
            name: longping-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-port
          initialDelaySeconds: 30
        readinessProbe:
          httpGet: 
            path: /readyz
            port: http-port
          initialDelaySeconds: 30
      securityContext:
        sysctls:
        - name: net.ipv4.ping_group_range
          value: "0 2147483647"